Modify workflow content-1a

diff --git a/.github/workflows/azure-keyvault-pipeline.yml b/.github/workflows/azure-keyvault-pipeline.yml
--- a/.github/workflows/azure-keyvault-pipeline.yml
+++ b/.github/workflows/azure-keyvault-pipeline.yml
@@ -1,13 +1,16 @@
 name: Azure Key Vault Secrets Example
 
-on: [push]
+on:
+  push:
+    branches:
+      - main
 
 jobs:
   fetch-secrets:
     runs-on: ubuntu-latest
     steps:
       - name: Check out the repository
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
 
       - name: Azure Login
         uses: azure/login@v1
@@ -17,11 +20,20 @@ jobs:
       - name: Get secrets from Azure Key Vault
         id: get-secrets
         run: |
+          set -Euoupipefail
           SECRET_VALUE=$(az keyvault secret show --name aznpadevkey --vault-name gstvo2k15labkvault --query value -o tsv)
+
+          if [[ -z "$SECRET_VALUE" ]]
+            then
+              echo "Error: No se obtuvo un valor del Key Vault" >&2
+              exit 1
+          fi
+
+          echo "::add-mask::$SECRET_VALUE"
           echo "SECRET_VALUE=$SECRET_VALUE" >> $GITHUB_ENV
 
       - name: Print Secret (for debugging purposes)
-        run: echo "The secret value is ${{ env.SECRET_VALUE }}"
+        run: echo "The secret value is set and masked."
 
       - name: Install Ansible
         run: sudo apt-get update -yqq && sudo apt-get install -yqq ansible
